version: "3.7"

# YAML Anchors

x-elastic-client-env: &elastic-client-env
  ELASTIC_HOST: ${ELASTIC_HOST:-elastic}
  ELASTIC_PORT: ${ELASTIC_PORT:-9200}
  ELASTIC_USER: ${ELASTIC_USER:-elastic}
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}

x-rethinkdb-client-env: &rethinkdb-client-env
  RETHINKDB_HOST: ${RETHINKDB_HOST:-rethink}
  RETHINKDB_PORT: ${RETHINKDB_PORT:-28015}
  RETHINKDB_DB: ${RETHINKDB_DB:-place_development}

services:
  test:
    image: placeos/service-spec-runner
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml.input
    depends_on:
      - elastic
      - rethink
    environment:
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      # Service Hosts
      <<: [*elastic-client-env, *rethinkdb-client-env]

  elastic:
    image: elasticsearch:7.17.6
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: true
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-changeme}

  rethink:
    image: rethinkdb:${RETHINKDB_VERSION:-2.4}
    restart: always
