# YAML Anchors

x-elastic-client-env: &elastic-client-env
  ELASTIC_HOST: ${ELASTIC_HOST:-elastic}
  ELASTIC_PORT: ${ELASTIC_PORT:-9200}

x-postgresdb-client-env: &postgresdb-client-env
  PG_HOST: ${PG_HOST:-postgres}
  PG_PORT: ${PG_PORT:-5432}
  PG_DB: ${PG_DB:-place_development}
  PG_USER: ${PG_USER:-postgres}
  PG_PASSWORD: ${PG_PASSWORD:-password}
  PG_DATABASE: ${PG_DATABASE:-place_development}
  PG_DATABASE_URL: ${PG_DATABASE_URL:-postgresql://postgres:password@postgres:5432/place_development}

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-latest}
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/shard.override.yml:/app/shard.override.yml
      - ${PWD}/shard.yml:/app/shard.yml.input
    depends_on:
      - elastic
      - postgres
      - migrator
    environment:
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      # Service Hosts
      <<: [*elastic-client-env, *postgresdb-client-env]

  elastic:
    image: elasticsearch:${ELASTIC_VERSION:-7.17.6}
    restart: always
    hostname: elastic
    healthcheck:
      test: wget -q --no-verbose --tries=1 --spider http://localhost:9200/_cat/health
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m

  postgres:
    hostname: postgres
    image: postgres:${POSTGRES_VERSION:-18}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: place_development

  migrator:
    build:
      context: ${PWD}/spec/migration
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:-18}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GITHUB_ACTION: ${GITHUB_ACTION:-}
      PG_DATABASE_URL: ${PG_DATABASE_URL:-postgresql://postgres:password@postgres:5432/place_development}
