require "pg-orm"
require "../src/neuroplastic"

# Spec models
####################################################################################################

abstract class AbstractBase < ::PgORM::Base
  include Neuroplastic
end

class TestBase < ::PgORM::Base
  include Neuroplastic
  default_primary_key id : UUID, autogenerated: true
  attribute owns : String = "all your bases"
end

class Basic < AbstractBase
  default_primary_key id : UUID, autogenerated: true
  attribute name : String, es_subfield: "keyword"
end

class Goat < AbstractBase
  default_primary_key id : UUID, autogenerated: true
  attribute name : String
  attribute teeth : Int32 = 0
  attribute job : String = "being a goat"
end

class Child::Kid < AbstractBase
  default_primary_key id : UUID, autogenerated: true
  attribute age : Int32 = 0
  attribute hoof_treatment : String = "oatmeal scrub"
  attribute visits : Array(String) = [] of String

  attribute goat_id : UUID, parent: "Goat"
  belongs_to :goat
end
