name: CI
on:
  push:
  schedule:
    - cron: "0 1 * * 0" # Every Sunday at 1:00
jobs:
  test:
    name: "Run spec suite"
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false

  crystal-style:
    name: "Check crystal style"
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main
